In [1]:
# import pandas
import pandas as pd

In [5]:
data = [12,3,4,5,54]
series = pd.Series(data)
print(series)

0    12
1     3
2     4
3     5
4    54
dtype: int64


In [7]:
data = [2,3,4,5,6]
i = ["A","B","C","D","E"]
series = pd.Series(i)
print(series)

0    A
1    B
2    C
3    D
4    E
dtype: object


In [9]:
data = {'a':10,'b':67,'c':89}
series = pd.Series(data)
print(series)

a    10
b    67
c    89
dtype: int64


In [11]:
series.replace(10,89)

a    89
b    67
c    89
dtype: int64

In [15]:
import numpy as np
data = np.array([100,123,452])
series = pd.Series(data,index=['a','b','c'])
print(series)

a    100
b    123
c    452
dtype: int32


In [17]:
import pandas as pd
data = {'Name': ['Alice','Bob','Marry'], 'Age': [25,30,34], 'Country': ['USA','UK','JAPAN']}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2  Marry   34   JAPAN


In [19]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=["G","S","B"])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   G  S  B
0  1  2  3
1  4  5  6
2  7  8  9
